name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: write

jobs:
  lint:
    name: Run ESLint Scan
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/_setup

      - name: Run ESLint
        run: npm run lint:ci

      - name: Upload analysis results to GitHub
        # Always run this step to upload the report, even if the lint step fails
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Setup Environment
        uses: ./.github/actions/_setup

      - name: Run Tests
        run: npm run test:coverage

      - name: Add coverage comment to PR
        if: github.event_name == 'pull_request'
        uses: davelosert/vitest-coverage-report@v2
        with:
          json-summary-path: ./coverage/coverage-summary.json

  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Setup Environment
        uses: ./.github/actions/_setup

      - name: Build backend project
        run: npm run build:backend

  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Setup Environment
        uses: ./.github/actions/_setup

      - name: Build frontend project
        run: npm run build:frontend
