name: Build and Deploy to Release Branch

on:
  push:
    branches:
      - main

  workflow_dispatch: # allow manual starts via GitHub

permissions:
  contents: write

jobs:
  build-and-commit:
    name: Build and Commit to Release Branch
    runs-on: ubuntu-latest

    # skip if the commit was made by this action
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.DEPLOY_GPG_KEY }}

      - name: Setup Environment
        uses: ./.github/workflows

      - name: Build project for distribution
        run: npm run build

      - name: Commit and push dist folder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '87113906+Mephisto5558@users.noreply.github.com'
          git config --global user.signingkey ${{ steps.import_gpg.outputs.keyid }}
          git add -f dist
          if ! git diff --staged --quiet; then
            git commit -S -m "build: Generate distributable files [skip ci]"
            git push --force origin HEAD:release
          else
            echo "No changes to commit."
          fi
