name: Build and Commit Dist

on:
  push:
    branches:
      - main

  workflow_dispatch: # allow manual starts via GitHub

permissions:
  contents: write

jobs:
  build-and-commit:
    name: Build and Commit Dist
    runs-on: ubuntu-latest

    # skip if the commit was made by this action
    if: "contains(github.event.head_commit.message, '[skip ci]') == false"

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project for distribution
        run: npm run build

      - name: Commit and push dist folder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f dist
          if ! git diff --staged --quiet; then
            git commit -m "build: Generate distributable files [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
